### PR TITLE
Add acknowledged, resolved user information on webhook payload

### LINKED ISSUE #4126: Expand user elements inside webhook payloads
### What would you like to see!

Currently when sending a webhook from OnCall the alert group has fields for users populated by IDs.  It would be much easier to use in templates if these IDs were expanded to the actual user information.
Current:
```
 "alert_group": {
    ...snip
    "resolved_by": "UP8HR335K2NZ3",
    ...snip
    "acknowledged_by": "UP8HR335K2NZ3",
    ...snip
  },
```

Expanded:
```
 "alert_group": {
    ...snip
    "resolved_by": {
      "id": "UP8HR335K2NZ3",
      "username": "user1",
      "email": "user1@company.com"
    }
    ...snip
    "acknowledged_by": {
      "id": "UP8HR335K2NZ3",
      "username": "user1",
      "email": "user1@company.com"
    }
    ...snip
  },
```

It may also be worth doing this for the integration element as well.

### Product Area

Alert Flow & Configuration

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by ravishankar15**
# What this PR does
Adds acknowledged and resolved user information to the web hook payload

## Which issue(s) this PR closes

Closes #4126 

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [x] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] Added the relevant release notes label (see labels prefixed w/ `release:`). These labels dictate how your PR will
    show up in the autogenerated release notes.

### CODE REVIEW

**Comment by ravishankar15** [comment]
I have added the details separately outside of the alertgroup since we use the same alert group serializer for the public API response. For integration details also we have followed the similar pattern.

**Review by joeyorlando — APPROVED** [review]
LGTM 👍 thanks again for your continued contributions @ravishankar15

**Review by joeyorlando — COMMENTED** [review]
actually, one last minor ask. Do you mind updating [the documentation](https://grafana.com/docs/oncall/latest/configure/outgoing-webhooks/#outgoing-webhook-templates) [here](https://github.com/grafana/oncall/blob/dev/docs/sources/configure/outgoing-webhooks/index.md#outgoing-webhook-templates)?

once that's squared away I will go ahead and merge ✌️

**Review by matiasb — APPROVED** [review]
Looks good, thanks!

**Review by alyssawada — APPROVED** [review]

**Pull request merged**
