### PR TITLE
Add dot between integration name and alert title in phone call

### PR DESCRIPTION
**Pull request by Konstantinov-Innokentii**
**What this PR does**:
Add dot between integration name and alert title in phone call, to make it more clear

**Which issue(s) this PR fixes**:
https://github.com/grafana/oncall/issues/851

### CODE REVIEW

**Review by iskhakov — APPROVED** [review]

**Comment by iskhakov** [comment]
Assuming this is for the additional delay
May be we can change the speed of the whole text in twilio?

**Review by greatvovan — COMMENTED** [review]
Looking at the template, I see that the fields are not confused as I originally assumed in #851, but there is probably another factor that contributes to the strange message we hear. What could be an example of `integration_name`? Can it be not raw name as specified in the UI but contain dots or commas?

**Comment by greatvovan** [comment]
In this example:
https://soundcloud.com/fun-with-no-end/grafana-oncall-sample-notification
The only variant to disassemble the message is seemingly this:
`integration_name` = Test web hook
`title` = Congratulations
`alert_count` = 1

But how to explain the value of `integration_name`? Can it come as "Test, web hook" or "Test. Web hook" by chance? How otherwise explain the pause between "test" and "web hook"?

**Review by Matvey-Kuk — APPROVED** [review]
Approve this change or here is my proposal:

"That's Grafana OnCall. Escalation (title) from integration (integration name) triggered (alert count) times."

**Comment by greatvovan** [comment]
As per discussion in #851, a part of the problem is that `integration_name` is not really integration name, but (integration name + type). In my opinion, they should not be concatenated and must be passed into the template as independent fields, to have a freedom of composing the message.

**Comment by greatvovan** [comment]
For example, I would like it to hear as "Alert via {integration_type} integration {integration_name}, title {title}, triggered {alert_count} times". Currently we do not have such a freedom. Also no accounting for singular/plural form of "time".

Templated example: "Alert via Prometheus integration Production cluster, title CPU usage, triggered 1 time".

**Comment by Konstantinov-Innokentii** [comment]
Stale

**Pull request closed without merging**
