### PR TITLE
Add Makefile command to make migrations

### PR DESCRIPTION
**Pull request by scubbo**
Apologies if I've missed it, but I couldn't find an existing command to create/update the `migrations/` directory contents based on changes to the Django models.

### CODE REVIEW

**Review by iskhakov — APPROVED** [review]

**Comment by joeyorlando** [comment]
@scubbo do you mind just adding this command to the list of `make` commands in `./dev/README.md`? 😄

**Comment by scubbo** [comment]
README updated! :)

I should highlight that there's [something wrong the Make setup on my local environment](https://github.com/grafana/oncall/issues/239#issuecomment-1317830381) - I have been able to successfully run the `make-migrations` command in this PR at least once, but I've also had it fail (on apparently identical setup) as well. This might be to do with my Make setup problems, or because I'm just doing something wrong related to the migrations (this is my first time working with Django) - either way, please do check for yourself on your own setups that this command works as-expected before accepting it, don't just take my word for it!

**Comment by joeyorlando** [comment]
> do check for yourself on your own setups that this command works as-expected before accepting it

This looks good to me. `make backend-migrate` is working successfully for me locally (after resolving a `pip` dependency M1 Mac specific issue in #877).

Come to think of it though, we _may_ want to do something like this instead:
```Makefile
backend-manage-command:
	$(call backend_command,python manage.py $(CMD))
```

and invoking as such:
```shell
make backend-manage-command CMD="makemigrations"
```

Reason being that we would eventually end up with one `make` command for each Django manage command. This approach would allow the `make` command to be a bit more dynamic. AFAIK `make` does not support doing something like `make backend-manage-command makemigrations`, hence the `CMD` argument.

**Comment by joeyorlando** [comment]
@scubbo just out of curiosity, and to gather feedback on the local setup, what is missing with the `docker-compose` setup that you run the API/celery workers outside of docker?

For example, I know some folks use PyCharm and connect the debugging tools to their server/celery workers (PyCharm _does_ have support to connect to a remote `docker-compose` Python interpreter, but there is currently a [JetBrains bug filed](https://youtrack.jetbrains.com/issue/PY-52173) which prevents it from working with `COMPOSE_PROFILES`, which we are using).

**Comment by scubbo** [comment]
> Come to think of it though, we may want to do something like this instead:

Ahhh! Yeah, that makes a lot of sense. Initially I was looking for a `make` command to run arbitrary `manage.py` commands, but I couldn't figure out how to plumb parameters (that is, command-names) to `make` itself (I've only recently left a BigTech company where all the Builder Tools were proprietary, so I'm learning Open Source tools as I go. Env variables were, in hindsight, an obvious choice 🙃)

I'll go ahead and make that change.

> just out of curiosity, and to gather feedback on the local setup, what is missing with the `docker-compose` setup that you run the API/celery workers outside of docker?

1. Nothing's missing from docker-compose - I just find that wrapping common `docker-compose` commands in a single `make` command is simpler (and, my reading of the `dev/README.md` file suggested that `make` was the "blessed" approach). But, I think I've miscommunicated somewhere, because...
2. ...I'm not (intentionally?) running API/celery workers outside of docker - they're still started up with `make start` which, AFAICT, does start them in docker (that is - `oncall_celery` shows up in `docker ps`). Though, as I noted [here](https://github.com/grafana/oncall/issues/846), I have had to set `COMPOSE_PROFILES` to start _all_ services, since the `depends_on` behaviour didn't seem to actually work with my older version of `docker-compose`. This meant that `oncall_celery` gets started by `make start`, while it doesn't appear to with the default `COMPOSE_PROFILES`

So, to cut through those complications and local-issues - my ideal situation would be that I can run `make start` (or `make init start` the first time around) which would result in everything starting up (in Docker) that I need.

**Comment by joeyorlando** [comment]
closing as this has been implemented in #886. Thanks for your contribution @scubbo!

**Pull request closed without merging**
