### PR TITLE
Helm chart: added configuration of uwsgi using environment variables

### PR DESCRIPTION
**Pull request by alexintech**
# What this PR does

Adds `uwsgi` configuration to helm chart.
Sets environment variables with name capitalized and prefixed with `UWSGI_`, and dashes are substituted with underscores like described [here](https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables)

Sets `UWSGI_LISTEN=1024` by default, but can be overwritten or completely removed by `uwsgi: null`

Or is it better to not specify default value (it's not backward compatible)?

Also, small indentation fixes for postgresql configuration.

## Which issue(s) this PR fixes

closes https://github.com/grafana/oncall/issues/562

Also, [this PR](https://github.com/grafana/oncall/pull/856) has been closed because of this PR

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Review by joeyorlando — APPROVED** [review]
nice! thanks for your continued contribution to improving the Helm charts @alexintech

**Comment by jrossBah** [comment]
@alexintech Big question for ya. I am currently working with getting grafana oncall implemented and we had to turn this setting down to 128 to get it to work in our kubernetes cluster. I am wondering why you default set it to 1024. As We understand it the container the chart spins up defaults to 128. We found this by changing it on the ec2 instance and still seeing the error until we lowered this new uwsgi setting.

Do you know is there a way in these values that changes the container default? Thank you!

**Comment by alexintech** [comment]
> @alexintech I am wondering why you default set it to 1024. 
> 
> Do you know is there a way in these values that changes the container default? Thank you!

@jrossBah That's not my decision. 1024 has been hardcoded in helm chart. I only made this value configurable. To maintain the same behavior default value remained the same.

**Comment by jrossBah** [comment]
> > @alexintech I am wondering why you default set it to 1024.
> > Do you know is there a way in these values that changes the container default? Thank you!
> 
> @jrossBah That's not my decision. 1024 has been hardcoded in helm chart. I only made this value configurable. To maintain the same behavior default value remained the same.

That's so interesting. What we found is that this limit seems to conflict with the limitations of the kubernetes and also docker containers that set at 128. So unless you bring this down to 128 or under the engine pods will fail.

**Pull request merged**
