### PR TITLE
docs: update notifications wording

### PR DESCRIPTION
**Pull request by brojd**
# What this PR does

update notifications wording

## Which issue(s) this PR closes

Related to https://github.com/grafana/oncall/issues/3104 

## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [x] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] Added the relevant release notes label (see labels prefixed w/ `release:`). These labels dictate how your PR will
    show up in the autogenerated release notes.

### CODE REVIEW

**Comment by alyssawada** [comment]
Hey @brojd! I'm catching up on the context of these updates. Is this wording changing within the product and UI copy as well? We want to be careful about any mismatches or inconsistencies around what we call things. I know in the mobile app, we still call this "Notification Policies," and in the Web UI, we use both "Notification settings" and "Notification policies." I don't see anywhere that we refer to these as "Notification rules." What prompted this update?

**Review by iskhakov — APPROVED** [review]

**Comment by brojd** [comment]
Hey @alyssawada ! Thanks for catching up. So that's the source of the changes, it was discussed with @mackgorski and @raphael-batte :
https://github.com/grafana/oncall/issues/3104

The web UI change is about to be released as part of https://github.com/grafana/irm/pull/126

[And I talked to ](https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1726585234067639)mobile team - mobile app will align too

Is that ok?

**Comment by alyssawada** [comment]
> Hey @alyssawada ! Thanks for catching up. So that's the source of the changes, it was discussed with @mackgorski and @raphael-batte : #3104
> 
> The web UI change is about to be released as part of [grafana/irm#126](https://github.com/grafana/irm/pull/126)
> 
> [And I talked to ](https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1726585234067639)mobile team - mobile app will align too
> 
> Is that ok?

Hey @brojd, thanks for the context. After chatting with @mackgorski about it this morning, I think wider discussions with IRM stakeholders around terminology decisions could be useful and help us coordinate updates better. We can go ahead and push these updates to support the product changes, but there are many other mentions of notification policies throughout the OnCall docs, so those will need to be addressed as well. I can add it to my backlog for now.

**Review by alyssawada — APPROVED** [review]
Product changes are merged so LGTM. I'll create a follow-up issue to update this terminology throughout the rest of the docs.

**Pull request merged**
