### PR TITLE
add API support for user timezone and working hours

### PR DESCRIPTION
**Pull request by vadimkerr**
Add internal API support for timezone and working hours configuration.

### CODE REVIEW

**Review by Konstantinov-Innokentii — APPROVED** [review]

**Comment by maskin25** [comment]
Frontend will expect new fields "tz" and "working_hours" in user model, like
```
.....
tz: "Europe/Moscow"
working_hours: {
            monday: [{ start: '09:00:00', end: '18:00:00' }],
            tuesday: [{ start: '09:00:00', end: '18:00:00' }],
            wednesday: [{ start: '09:00:00', end: '18:00:00' }],
            thursday: [{ start: '09:00:00', end: '18:00:00' }],
            friday: [{ start: '09:00:00', end: '18:00:00' }],
            saturday: [],
            sunday: [],
          },
```
have you added this fields in that way?

**Comment by maskin25** [comment]
@vadimkerr  merge please your this branch to `new-schedules` branch

**Comment by vadimkerr** [comment]
> Frontend will expect new fields "tz" and "working_hours" in user model, like
> 
> ```
> .....
> tz: "Europe/Moscow"
> working_hours: {
>             monday: [{ start: '09:00:00', end: '18:00:00' }],
>             tuesday: [{ start: '09:00:00', end: '18:00:00' }],
>             wednesday: [{ start: '09:00:00', end: '18:00:00' }],
>             thursday: [{ start: '09:00:00', end: '18:00:00' }],
>             friday: [{ start: '09:00:00', end: '18:00:00' }],
>             saturday: [],
>             sunday: [],
>           },
> ```
> 
> have you added this fields in that way?

yup, but use "timezone" instead of "tz"

**Comment by vadimkerr** [comment]
Ok closing this PR and merging the branch to `new-schedules`

**Pull request merged**
