### PR TITLE
Add simple smtp email messaging backend

### PR DESCRIPTION
**Pull request by matiasb**
Simple email messaging backend, using Django `send_mail` setup.
There is room for improvement, this is a really simple/basic implementation.

**To try it**

1. Set the following variables in your .env file (or environment variables):
```
ENABLE_SMTP_EMAIL_BACKEND = True
EMAIL_HOST = <email host>
EMAIL_HOST_USER = <email host username>
EMAIL_HOST_PASSWORD = <email host password>
EMAIL_PORT = <email port, defaults to 587>
EMAIL_USE_TLS = <enable tls, defaults to False>
```
2. You can now choose "Email" as a notification option in your user's profile.
3. Notifications will be sent to the set user email address, and will use the existing email templates.

### CODE REVIEW

**Comment by Konstantinov-Innokentii** [comment]
Reusing messaging backend is great, but maybe we want  use existing sendgrid app instead of django  send_mail?

**Comment by acr-varonis** [comment]
I agree with @matiasb for our use case we have an on-prem SMTP server with authentication that we want to utilize to send notifications.

**Comment by acr-varonis** [comment]
Any updates on this PR ? 
I would love for this to get merged so i can use it in production.

thanks.

**Comment by matiasb** [comment]
Closing this one since the feature got implemented by #621 :rocket:

**Pull request closed without merging**
