### PR TITLE
Add setting for alert group log notification in slack

### LINKED ISSUE #3849: Ability to disable "Alert Group log" on the Slack integration
### What would you like to see!

I have not been able to find an option to disable the "Alert group log" on the Slack messages generated. It makes the Slack threads functionality pretty much useless by creating and updating a thread with your mention on it that also generates an undesired notification. Would it be possible to add a toggle for the Slack integration to disable the addition of the threaded message? 

Here's how 99% of my threads window looks like in Slack as is:
image

### Product Area

Alert Flow & Configuration

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by ravishankar15**
# What this PR does
Adds a new setting that controls alert group log display in slack threads

Screenshot 2024-03-01 at 8 08 57 PM

## Which issue(s) this PR fixes
Fixes #3849

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Comment by joeyorlando** [comment]
@ravishankar15 thanks for all of your recent ideas/contributions 🙏 the core team discussed your contribution and we don't have any _immediate_ plans to add this to the product, but we might _possibly_ implement something similar in the near future. I'm going to close this PR for now, but thanks again for your effort!

**Comment by salarali** [comment]
Any details on the future plans? I would have been really interested in this feature.

**Comment by karl-johan-grahn** [comment]
Can we please re-open this PR or work on adding it to the product ASAP?

**Comment by karl-johan-grahn** [comment]
Without this feature, we almost have to disable Slack notifications for integrations because Slack threads become bloated with notifications

**Comment by karl-johan-grahn** [comment]
@joeyorlando

**Comment by joeyorlando** [comment]
@karl-johan-grahn keep an eye on https://github.com/grafana/oncall/issues/3849 🙂

**Pull request closed without merging**
