### PR TITLE
Add doc-validator workflow

### PR DESCRIPTION
**Pull request by jdbaldry**
`doc-validator` codifies best practices for technical documentation at Grafana.
Linting errors are defined in
https://github.com/grafana/technical-documentation/blob/main/tools/cmd/doc-validator/errata.hcl.

The errors enumerated in the errata file are under active development and are intended to be helpful in explaining reasoning and fixes for linting issues.

Not all errors meet this goal yet, so please report any errors that are confusing, seem to lack motivation, or are hard to resolve.

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by joeyorlando** [comment]
@jdbaldry we have a [`pre-commit` step](https://github.com/grafana/oncall/blob/dev/.pre-commit-config.yaml#L109-L111) which runs `markdownlint` against `./docs`. Would you recommend we turn that off in favour of these checks?

**Comment by jdbaldry** [comment]
Hey @joeyorlando, I'd say the two are complementary. `doc-validator` is more of a linter of technical documentation than of the Markdown itself.

**Review by joeyorlando — APPROVED** [review]
great idea! thanks for adding this @jdbaldry 👍

**Review by alyssawada — APPROVED** [review]
Thanks for taking care of this, Jack!

**Comment by jdbaldry** [comment]
I need to fix some canonical front matter validation and then I will open this PR for review.

**Comment by jdbaldry** [comment]
I believe this is now ready for review. The errors reported by the validator can be seen in https://github.com/grafana/oncall/actions/runs/4232345624/jobs/7351966975 and will need fixing before this can be merged.

**Comment by joeyorlando** [comment]
does someone from @grafana/docs-oncall want to volunteer to patch these validation errors?

**Comment by joeyorlando** [comment]
@jdbaldry or @alyssawada did we want to merge this in?

**Comment by jdbaldry** [comment]
I can spend a half hour now trying to clean up the errors so we can merge this.

**Comment by joeyorlando** [comment]
is this PR still relevant or should it be closed?

**Comment by jdbaldry** [comment]
I believe there has been a move away from having a technical writer on this project. This CI workflow requires a technical writer to fix the linting issues identified so I'll close this until there are resources to apply the fixes.

**Pull request closed without merging**
