### PR TITLE
Fixing helm hooks for install stage

### PR DESCRIPTION
**Pull request by MrEcco**
# What this PR does

## Issue

At the first run (`helm install ...`) the migration job cannot start the container because cannot find Postgres/Redis/MySQL credentials and ServiceAccount.

Workaround: set `.migrate.useHook` value to `false` for the `install` stage, and after you can switch back to `true`.

This PR completely resolves this issue.

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated (doesn't violate anything)
- [x] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)
- [x] It is manually tested in the internal environment

### CODE REVIEW

**Comment by MrEcco** [comment]
@matiasb @joeyorlando Could you please guys take a look? And please add `pr:no public docs` and `pr:no changelog` labels.

**Comment by MrEcco** [comment]
ping

This is not a stale PR, just ignored yet..

**Comment by iskhakov** [comment]
@MrEcco thank you for the contribution, looks good to me. Could you please add helm unittests similar to [this](https://github.com/grafana/oncall/blob/dev/helm/oncall/tests/mysql_env_test.yaml) before the PR get merged?

**Comment by MrEcco** [comment]
@iskhakov Done, now with relevant tests. Please review and merge :)

Could you please add the mentioned in the PR labels? Pipeline tests cannot be passed without these labels.

**Comment by joeyorlando** [comment]
Hi there @MrEcco if you can address [the `yamllint` issues](https://github.com/grafana/oncall/actions/runs/6946186975/job/18897086684?pr=3136#step:7:123) I'll get this merged in 😄

**Review by joeyorlando — APPROVED** [review]

**Pull request merged**
