### PR TITLE
Add region_slug column to organization

### PR DESCRIPTION
**Pull request by mderynck**
Add column to keep track of region in organization.

### CODE REVIEW

**Comment by mderynck** [comment]
https://github.com/grafana/oncall-private/issues/1078

**Review by Konstantinov-Innokentii — APPROVED** [review]

**Comment by Konstantinov-Innokentii** [comment]
Is that regionSlug coming from grafana, right?

**Review by joeyorlando — APPROVED** [review]

**Comment by mderynck** [comment]
> Is that regionSlug coming from grafana, right?

regionSlug is from gcom instance info.

**Comment by mderynck** [comment]
Going to expand this into other region migration work instead of adding it standalone.

**Pull request closed without merging**
