### PR TITLE
Secrets consistency for the chart

### PR DESCRIPTION
**Pull request by ksa-real**
- Enabling existing secrets for external MySQL and Redis
- Tolerate existing secrets for bundled charts.
- README.md: secrets handling explained.
- Fixed multiple bugs where missing required field was replaced with default instead of failing.
- PHONE_NOTIFICATIONS_LIMIT was on the wrong level: it was not set if existingSecret was true.

Next are the cosmetic changes. They improve chart consistency, e.g. prevent generation of multiple new lines in certain cases:
- Common approach to spaces trimming. This typically allows curly blocks and actual strings indentation and nice `nindent` usage:
  - Two curly blocks should not trim the same space. I.e. "{{ ... -}} {{- ... }}" shouldn't happen.
  - Template generates either single line or multiline string. In both cases, no new line appears on both sides of the output string. So we delete unnecessary new lines inside and at the end of string with "trim-to-left" (`{{-` ) and the leading new line using "trim-to-right" (`-}}`).
    Note that trimming both leading and trailing new line is not  always easily possible: https://github.com/Masterminds/sprig/issues/357

    Example.

    ```
    {{- define "mytemplate" -}}
    {{ if someBoolean -}}
      {{ .Value.some }}
    {{- else -}}
      some string
    {{- end }}
    {{- end }}
    ```

- `template` replaced with `include`. It is often recommended to use `include` by default, as it allows pipelining.

## Checklist

- [ ] Tests updated - No tests for Helm chart
- [X] Documentation added
- [x] `CHANGELOG.md` updated

### CODE REVIEW

**Comment by matiasb** [comment]
At first sight, suggestions make sense to me. @iskhakov, would you take a look?

**Comment by ksa-real** [comment]
@iskhakov Friendly ping

**Comment by marcusteixeira** [comment]
Ac

**Comment by ksa-real** [comment]
Can someone take a look, please?

**Comment by ksa-real** [comment]
> Ac

Is it a common abbreviation? I wonder what it means in this context :)

**Comment by ksa-real** [comment]
@Matvey-Kuk @iskhakov Can you please assign this to someone?

**Comment by ksa-real** [comment]
Closed accidentally by pushing a version with incomplete rebase

**Comment by ksa-real** [comment]
After re-opening it triggered a lot of tests. I'll create another PR

**Comment by ksa-real** [comment]
ping

**Comment by iskhakov** [comment]
Hi @ksa-real thank you for the contribution. Would you please merge the latest dev and check if helm unit tests are passing. Overall looks great to me, will merge afterwards

**Comment by ksa-real** [comment]
Thanks! Will do tomorrow

**Review by iskhakov — CHANGES_REQUESTED** [review]
waiting for changes to pass tests

**Comment by ksa-real** [comment]
I have doubts about TWILIO_ACCOUNT_SID. IMO it should reside in existingSecret if such exists (as being a part of credentials).

**Comment by ksa-real** [comment]
@iskhakov Can you please approve the tests? Note that due to a single file accidental change (despite the later reversal) a bunch of unnecessary tests were triggered. Not sure if it is possible to remove them

**Comment by ksa-real** [comment]
@iskhakov Please, re-approve the workflows

**Comment by ksa-real** [comment]
I've fixed the tests. Everything seems to run fine in my forked workflow, except for e2e tests which are slow to be picked up by workers: [workflow](https://github.com/ksa-real/grafana-oncall/actions/runs/5344649445)

**Review by iskhakov — APPROVED** [review]

**Pull request merged**
