### PR TITLE
Bump celery version, telegram version

### PR DESCRIPTION
**Pull request by iskhakov**
I had to bump telegram library version as it was causing `celery==5.2.7` crash. 
With `python-telegram-bot==13.13` all works fine, @vadimkerr can you please take a look too?

The error was really unobvious
```
2022-09-01 09:41:37,107 source=engine:celery task_id=??? task_name=??? name=celery.bootsteps level=ERROR Error on stopping Pool: TypeError("__init__() missing 1 required positional argument: 'retry_after'")
```
As it was not able to close the connection pool all the other tasks were getting stuck as well, so the system remained partially operational until some point and was really difficult to debug.

I've tested different scenarios, alert workflow and other tasks seems to be working fine. The most important one works well:
1. Install celery 4.3.0
2. Create the alert with escalation in one minute
3. Stop the celery and update to 5.2.7 and restart it
4. Check if escalations continued

### CODE REVIEW

**Comment by iskhakov** [comment]
```
2022-09-01 09:41:37,082 source=engine:celery task_id=e8c9b3fa-46ce-4b3f-be86-fbdf945bc50c task_name=apps.telegram.tasks.register_telegram_webhook name=celery.app.trace level=INFO Task apps.telegram.tasks.register_telegram_webhook[e8c9b3fa-46ce-4b3f-be86-fbdf945bc50c] retry: Retry in 2s: RetryAfter()
2022-09-01 09:41:37,107 source=engine:celery task_id=??? task_name=??? name=celery.bootsteps level=ERROR Error on stopping Pool: TypeError("__init__() missing 1 required positional argument: 'retry_after'")
Traceback (most recent call last):
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
    message = load(bufv)
TypeError: __init__() missing 1 required positional argument: 'retry_after'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 148, in send_all
    fun(parent, *args)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 369, in stop
    return self.obj.stop()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/base.py", line 120, in stop
    self.on_stop()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 141, in on_stop
    self._pool.join()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/billiard/pool.py", line 1622, in join
    stop_if_not_current(self._result_handler)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/billiard/pool.py", line 145, in stop_if_not_current
    thread.stop(timeout)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/billiard/pool.py", line 526, in stop
    self.on_stop_not_started()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 359, in on_stop_not_started
    iterate_file_descriptors_safely(
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 214, in iterate_file_descriptors_safely
    hub_method(fd, *hub_args, **hub_kwargs)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 386, in _flush_outqueue
    task = reader.recv()
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/billiard/connection.py", line 279, in recv
    return ForkingPickler.loadbuf(buf)
  File "/Users/ildariskhakov/src/github.com/grafana/oncall/venv/lib/python3.9/site-packages/billiard/reduction.py", line 61, in loadbuf
    return cls.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'retry_after'
2022-09-01 09:41:37,124 source=engine:celery task_id=853f9815-5185-4ea6-bf92-a83edad9f6ee task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=root l
```

**Comment by Konstantinov-Innokentii** [comment]
@iskhakov So, RetryAfter works well?

**Comment by iskhakov** [comment]
Vadim confirmed that telegram 13.13 works fine

**Comment by iskhakov** [comment]
> @iskhakov So, RetryAfter works well?
yes, it works well with the new version

**Pull request merged**
