### PR TITLE
Social auth exception logging

### PR DESCRIPTION
**Pull request by dimitar-ivanov-93**
This will vastly improve troubleshooting when an unexpected error occurs.

# What this PR does
Enables logging of the exception that might be thrown by SocialAuthExceptionMiddleware. It vastly improves the speed and accuracy of troubleshooting requests to external applications with the aim to authenticate, since there is usually no response to look at. 
## Which issue(s) this PR fixes
Closes [#2035](https://github.com/grafana/oncall/issues/2035)
## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Comment by Konstantinov-Innokentii** [comment]
@dimitar-ivanov-93 thanks for the contribution. Could you please change wording for logger:
"SocialAuthAuthCanceledExceptionMiddleware.process_exception: {exception}"

The reason behind this is the exception is not unhandled, we are handling them right on next lines.

**Comment by dimitar-ivanov-93** [comment]
Sure, that makes sense to me. Editing now.

**Review by Konstantinov-Innokentii — APPROVED** [review]

**Comment by Konstantinov-Innokentii** [comment]
@dimitar-ivanov-93 approved, thanks. However CI is failing on linting step, could you please run ```make lint``` and push the changes?

**Comment by dimitar-ivanov-93** [comment]
@Konstantinov-Innokentii I have run 'make lint' and pushed as per your request.

**Comment by Konstantinov-Innokentii** [comment]
@dimitar-ivanov-93 lint is still failing with:
```
E     File "/home/runner/work/oncall/oncall/engine/apps/social_auth/middlewares.py", line 22
E       	if exception:
E       ^
E   TabError: inconsistent use of tabs and spaces in indentation
```
and
```
error: cannot format engine/apps/social_auth/middlewares.py: cannot use --safe with this file; failed to parse source file AST: inconsistent use of tabs and spaces in indentation (<unknown>, line 22)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```
So, core problem is in the tabs/spaces near if exception (I'm wondering why linter didn't fix it, but fails, which python version are you using?)
Anyway, could you please use tabs near `if exception` line.

**Comment by dimitar-ivanov-93** [comment]
Apologies for the delay. I am using python version 3.10.10
I believe the issue was caused by me irresponsibly using a nano editor, I have now opened the file in VSCode and replaced spaces with tabs, which made lint output this to me:
```
reformatted engine/apps/social_auth/middlewares.py

All done! ✨ 🍰 ✨
1 file reformatted, 737 files left unchanged.
```

I hope this solves the issue.
@Konstantinov-Innokentii Could you be so kind as to run the tests again, please?

**Pull request merged**
