### PR TITLE
Fix slack notifications not displaying properly

### PR DESCRIPTION
**Pull request by mderynck**
#167 

Use text fallback field in all places where attachments and blocks are used. Replace attachments with blocks in some cases so text is not repeated in both.

Blocks do not support having the colored line on the left.  Alternatively we could use a colored dot emoji.

From slack docs:
> Any content displayed within attachments may be wrapped, truncated, or hidden behind a "show more" style option by Slack clients. This isn't the case with the top-level blocks field.

### CODE REVIEW

**Comment by iskhakov** [comment]
Added block or text field to each postMessage and update

**Comment by mderynck** [comment]
I tested the most recent set of changes on Ubuntu and Android. All the messages displayed properly when displaying as notifications or mentions & reactions.

**Comment by Matvey-Kuk** [comment]
@mderynck could you please provide screenshots of how Slack messages look after update?

**Comment by mderynck** [comment]
Current (Android Mentions & Reactions) - I think the slack client was updated so they appear blank instead of "Content cannot be displayed"

Before_Mention

Current (Android Thread)

Before_Thread

After (Android Mentions & Reactions) - Ignore the bot icon, mine is customized so I can tell different versions apart

After_Mention

After (Android Thread)

After_Thread

**Comment by iskhakov** [comment]
Merging

**Pull request merged**
