### PR TITLE
Add slack DM personal notification policy option

### LINKED ISSUE #3874: Add the ability to choose between Slack mention or Slack direct message for user notification / ping
### What would you like to see!

I envision sending a Slack message instructing users to check the designated alert Slack channel, akin to the Slack direct message Oncall sends when the user lacks access to the alert's Slack channel. The problem with Slack mentions is their visibility only within threads. Threads consist of a flow of mentions, replies, and DMs. Busy periods frequently bury Slack mentions within threads, making them ineffective.

To address this, we can incorporate an additional DM option into the dropdown list on the user profile page, situated under default and important notifications.
note-options

Thanks

### Product Area

Chatops

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by ravishankar15**
# What this PR does

## Which issue(s) this PR fixes
Closes #3874 

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [x] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Comment by Konstantinov-Innokentii** [comment]
Not directly related to pr - maybe we want to completely move slack personal notifications to the DMs instead of thread?

**Comment by ravishankar15** [comment]
@Konstantinov-Innokentii You mean to replace the thread notification of users to DM ? That would reduce the team from having visibility of who is working on the OnCall ticket I believe.

**Review by joeyorlando — COMMENTED** [review]
consider updating the documentation around Slack [here](https://grafana.com/docs/oncall/latest/manage/notify/slack/)

**Comment by BitKickerBHS** [comment]
> @Konstantinov-Innokentii You mean to replace the thread notification of users to DM ? That would reduce the team from having visibility of who is working on the OnCall ticket I believe.

The team visibility should still be at the same level. The alert should arrive in the slack channel with a list of invited users correct? But this would just change the individual user notification from a mention that shows up in that users slack thread to a direct message from the Oncall Slack Bot, inviting them to look at the alert in the aforementioned slack channel.  Please let me know if I'm not understanding the workflow. 
-Thanks

**Comment by Konstantinov-Innokentii** [comment]
@BitKickerBHS Yep, that's what I meant. However, it's not something team is working on now, just my vision how it should work!

**Comment by ravishankar15** [comment]
Hi Team, Thanks if that behaviour is kind of like a next upgrade can we merge this PR since we don't have any open questions around this ?

**Review by alyssawada — APPROVED** [review]
LGTM on the documentation front. Will defer to the team for final approval :)

**Comment by joeyorlando** [comment]
@Konstantinov-Innokentii wdyt?

**Comment by Konstantinov-Innokentii** [comment]
@joeyorlando I wonder if we need to introduce an additional escalation step. I prefer to rework the Notify in Slack step to send notifications in DMs instead, just like @BitKickerBHS described. AFAIK there were no product decisions to do that, but  I'm advocating for that.

**Comment by ravishankar15** [comment]
@BitKickerBHS If the alert arrive in the slack channel with a list of invited users by default they will be notified in threads in slack. As part of this change we wanted to send a DM as well with the message correct ?

@joeyorlando / @Konstantinov-Innokentii I will go ahead and make the changes with a single step. Let me know if I should defer for a different approach.

**Comment by BitKickerBHS** [comment]
> @BitKickerBHS If the alert arrive in the slack channel with a list of invited users by default they will be notified in threads in slack. As part of this change we wanted to send a DM as well with the message correct ?
> 
> @joeyorlando / @Konstantinov-Innokentii I will go ahead and make the changes with a single step. Let me know if I should defer for a different approach.

I imagined the DM message would be instead of the threads notification but if both are necessary that would be fine.

**Comment by ravishankar15** [comment]
@joeyorlando / @Konstantinov-Innokentii  I have made the changes. We are already sending a DM notification when the user is not in the alert channel I added the implementation as an extension to the same.

**Comment by BitKickerBHS** [comment]
> @joeyorlando / @Konstantinov-Innokentii I have made the changes. We are already sending a DM notification when the user is not in the alert channel I added the implementation as an extension to the same.

bumping for visibility.

**Comment by BitKickerBHS** [comment]
Hello @ravishankar15 just checking to see if this change is still possible.
-Thanks

**Pull request closed without merging**
