### PR TITLE
fix: post to Telegram ChatOps channel option is not showing in the integration page

### PR DESCRIPTION
**Pull request by alexintech**
# What this PR does
Fix Post to Telegram ChatOps channel option is not showing in the integration page.

Problem has been introduced by [this PR](https://github.com/grafana/oncall/pull/2147/files)

## Which issue(s) this PR fixes
closes https://github.com/grafana/oncall/issues/2486

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Comment by alexintech** [comment]
👀

**Comment by alexintech** [comment]
Can anybody take a look, please?

**Comment by madima92** [comment]
Hi Team, 

Just to add on this, one of our customers is facing the same issue, can you please take a look?

**Comment by teodosii** [comment]
I'll have a look and merge it today

**Review by teodosii — APPROVED** [review]

**Pull request merged**
