### PR TITLE
add option for sidecar containers in helm chart

### PR DESCRIPTION
**Pull request by lu1as**
# What this PR does
Adds support for defining extra containers which run as sidecar alongside the celery and engine containers 

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Comment by iskhakov** [comment]
thank you for the contribution! Would you please add some helm unit tests

**Comment by lu1as** [comment]
@iskhakov I added unit tests and already found an issue 😄 It's fixed now.
I hope the tests are sufficient, it's the first time for me using this framework.

**Comment by lu1as** [comment]
I just added the option for `extraContainers` also for the migrate-job.

**Review by joeyorlando — APPROVED** [review]

**Comment by lu1as** [comment]
I rebased the source branch to resolve merge conflicts.
In the meantime I also noticed that using the cloud-sql-proxy does not work for this helm chart, because there is an init container which waits for the DB connection and prevents the sidecar from starting. Nonetheless, the option to add sidecars is useful, I guess.

**Pull request merged**
