### PR TITLE
package.json update

### PR DESCRIPTION
**Pull request by teodosii**
# What this PR does

## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

**Review by joeyorlando — COMMENTED** [review]
for the major version upgrades, are there any breaking changes that we need to be aware of?

**Comment by teodosii** [comment]
Just testing and see how it goes @joeyorlando - still in progress

**Review by joeyorlando — COMMENTED** [review]
imo this seems like a risky change to bundle all major version upgrades together. What about doing it little by little?

**Review by joeyorlando — CHANGES_REQUESTED** [review]
imo making this many major version upgrades, especially when we have low test coverage on the frontend, all at once seems incredibly risky. have you considered doing this in smaller chunks?

**Comment by joeyorlando** [comment]
@teodosii should we close this? (there are quite a few merge conflicts now)

**Comment by teodosii** [comment]
I updated grafana-ui, react and a few other but minor packages in a labels PR. Closing this one in the meanwhile, there's still plenty of packages left to be upgraded though.

**Pull request closed without merging**
